IGNITE-16424 [ducktests] add command to show logs from docker nodes

diff --git a/modules/ducktests/tests/docker/ducker-ignite b/modules/ducktests/tests/docker/ducker-ignite
--- a/modules/ducktests/tests/docker/ducker-ignite
+++ b/modules/ducktests/tests/docker/ducker-ignite
@@ -70,6 +70,7 @@ build [-j|--jdk JDK] [-c|--context] [image-name]
 
 up [-n|--num-nodes NUM_NODES] [-f|--force] [docker-image]
         [-C|--custom-ducktape DIR] [-e|--expose-ports ports] [-j|--jdk JDK_VERSION]
+        [--subnet SUBNET]
     Bring up a cluster with the specified amount of nodes (defaults to ${default_num_nodes}).
     The docker image name defaults to ${default_image_name}. If --force is specified, we will
     attempt to bring up an image even some parameters are not valid.
@@ -86,10 +87,18 @@ up [-n|--num-nodes NUM_NODES] [-f|--force] [docker-image]
     If --jdk is specified then we will use this argument as base image for ducktest's docker images.
     Otherwise ${default_jdk} is used.
 
+    If --subnet is specified then nodes are assigned IP addresses in this subnetwork. SUBNET is specified
+    in the CIDR format and passed directly to the docker create network command.
+
 test [test-name(s)]
     Run a test or set of tests inside the currently active Ducker nodes.
     For example, to run the system test produce_bench_test, you would run:
         ./tests/docker/ducker-ignite test ./tests/ignitetest/test/core/rebalance_test.py
+
+log [node-name]
+    Show ignite logs from node-name node using the lnav.  If node-name is not given, it prints
+    the names of all running nodes.  If node-name is 'all', we will show logs from all nodes.
+    If user-name is given, we will try to log in as  that user.  Otherwise, we will log in as the 'ducker' user.
 
 ssh [node-name|user-name@node-name] [command]
     Log in to a running ducker container.  If node-name is not given, it prints
@@ -333,6 +342,7 @@ ducker_up() {
             -f|--force) force=1; shift;;
             -n|--num-nodes) set_once num_nodes "${2}" "number of nodes"; shift 2;;
             -e|--expose-ports) set_once expose_ports "${2}" "the ports to expose"; shift 2;;
+            --subnet) set_once subnet "${2}" "subnet in CIDR format that represents a network segment"; shift 2;;
             *) set_once image_name "${1}" "docker image name"; shift;;
         esac
     done
@@ -349,6 +359,7 @@ use only ${num_nodes}."
             exit 1
         fi
     fi
+    [[ "${subnet}" ]] && docker_network_options="--subnet ${subnet}"
 
     docker ps >/dev/null || die "ducker_up: failed to run docker.  Please check that the daemon is started."
 
@@ -367,7 +378,7 @@ attempting to start new ones."
     if docker network inspect ducknet &>/dev/null; then
         must_do -v docker network rm ducknet
     fi
-    must_do -v docker network create ducknet
+    must_do -v docker network create "${docker_network_options}" ducknet
     if [[ -n "${custom_ducktape}" ]]; then
         setup_custom_ducktape "${custom_ducktape}" "${image_name}"
     fi
@@ -489,6 +500,37 @@ ducker_test() {
     exec docker exec --user=ducker ducker01 bash -c "${cmd}"
 }
 
+ducker_log() {
+    require_commands lnav
+    [[ $# -eq 0 ]] && die "ducker_log: Please specify a container name to show logs from. \
+Currently active containers: $(echo_running_container_names)"
+    local node_info="${1}"
+    shift
+    local user_name="ducker"
+    if [[ "${node_info}" =~ @ ]]; then
+        user_name="${node_info%%@*}"
+        local node_name="${node_info##*@}"
+    else
+        local node_name="${node_info}"
+    fi
+    if [[ "${node_name}" == "all" ]]; then
+        local nodes=$(echo_running_container_ip_addresses)
+        [[ "${nodes}" == "(none)" ]] && die "ducker_ssh: can't locate any running ducker nodes."
+        local nodes_list=""
+        for node in ${nodes}; do
+          nodes_list="${nodes_list} ${user_name}@${node}:/mnt/service/logs/ignite.log"
+        done
+        lnav /var/log/syslog ${nodes_list} || die "lnav ${nodes_list} failed"
+    else
+        local node_address=$(docker inspect --type=container "${node_name}" --format '{{ .NetworkSettings.Networks.ducknet.IPAddress }}')
+        if [[ -z "${node_address}" ]]; then
+            die "ducker_ssh: can't locate node ${node_name}. Currently running nodes: $(echo_running_container_names)"
+        else
+            lnav /var/log/syslog ${user_name}@${node_address}:/mnt/service/logs/ignite.log || die "lnav ${node_name} failed"
+        fi
+    fi
+}
+
 ducker_ssh() {
     require_commands docker
     [[ $# -eq 0 ]] && die "ducker_ssh: Please specify a container name to log into. \
@@ -534,6 +576,21 @@ echo_running_container_names() {
         echo "(none)"
     else
         echo ${node_names//$'\n'/ }
+    fi
+}
+
+echo_running_container_ip_addresses() {
+    node_ids="$(docker ps -f=network=ducknet -q)"
+    node_ids=${node_ids//$'\n'/ }
+    if [[ -z "${node_ids}" ]]; then
+        echo "(none)"
+    else
+        node_addresses="$(docker inspect --format '{{ .NetworkSettings.Networks.ducknet.IPAddress }}' $node_ids)"
+        if [[ -z "${node_addresses}" ]]; then
+            echo "(none)"
+        else
+            echo ${node_addresses//$'\n'/ }
+        fi
     fi
 }
 
@@ -652,7 +709,7 @@ shift
 case "${action}" in
     help) usage 0;;
 
-    build|up|test|ssh|down|purge|compare)
+    build|up|test|log|ssh|down|purge|compare)
         ducker_${action} "${@}"; exit 0;;
 
     *)  echo "Unknown command '${action}'.  Type '${script_path} --help' for usage information."
